#!/usr/bin/env python
"""Generate a lightweight API contract document for Android/backend collaboration."""
from __future__ import annotations

import re
from pathlib import Path


BACKEND_ROUTE_RE = re.compile(r'@app\.(get|post|put|delete)\("([^"]+)"\)')
ANDROID_ROUTE_RE = re.compile(r'@(GET|POST|PUT|DELETE)\("([^"]+)"\)')


def parse_backend_routes(app_py: Path) -> dict[tuple[str, str], str]:
    content = app_py.read_text(encoding="utf-8")
    routes: dict[tuple[str, str], str] = {}
    for method, path in BACKEND_ROUTE_RE.findall(content):
        routes[(method.upper(), path)] = "backend"
    return routes


def parse_android_routes(api_service: Path) -> dict[tuple[str, str], str]:
    content = api_service.read_text(encoding="utf-8")
    routes: dict[tuple[str, str], str] = {}
    for method, path in ANDROID_ROUTE_RE.findall(content):
        routes[(method.upper(), path)] = "android"
    return routes


def build_markdown(
    backend_routes: dict[tuple[str, str], str],
    android_routes: dict[tuple[str, str], str],
) -> str:
    all_routes = sorted(set(backend_routes) | set(android_routes), key=lambda item: (item[1], item[0]))
    lines = [
        "# Android API Contract",
        "",
        "This file is generated by `scripts/generate_android_api_contract.py`.",
        "",
        "## Route Matrix",
        "",
        "| Method | Path | Backend | Android | Status |",
        "| --- | --- | --- | --- | --- |",
    ]
    for method, path in all_routes:
        in_backend = (method, path) in backend_routes
        in_android = (method, path) in android_routes
        status = "OK" if in_backend and in_android else "Missing sync"
        lines.append(
            f"| `{method}` | `{path}` | {'Yes' if in_backend else 'No'} | {'Yes' if in_android else 'No'} | {status} |"
        )

    backend_only = sorted(set(backend_routes) - set(android_routes), key=lambda item: (item[1], item[0]))
    android_only = sorted(set(android_routes) - set(backend_routes), key=lambda item: (item[1], item[0]))

    lines.extend(
        [
            "",
            "## Sync Notes",
            "",
            f"- Backend route count: `{len(backend_routes)}`",
            f"- Android route count: `{len(android_routes)}`",
            f"- Backend only: `{len(backend_only)}`",
            f"- Android only: `{len(android_only)}`",
            "",
        ]
    )

    if backend_only:
        lines.append("### Backend Only")
        lines.append("")
        for method, path in backend_only:
            lines.append(f"- `{method} {path}`")
        lines.append("")

    if android_only:
        lines.append("### Android Only")
        lines.append("")
        for method, path in android_only:
            lines.append(f"- `{method} {path}`")
        lines.append("")

    lines.extend(
        [
            "## Collaboration Rules",
            "",
            "- Backend changes to `src/api/app.py` should regenerate this file before Android integration.",
            "- Android changes to `ApiService.kt` should run the contract test and smoke script before merge.",
            "- Real-device debugging should run `scripts/test_android_mobile_api.py` against the same base URL used in the app.",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    project_root = Path(__file__).resolve().parents[1]
    app_py = project_root / "src" / "api" / "app.py"
    api_service = project_root / "android_app" / "app" / "src" / "main" / "java" / "com" / "quant" / "system" / "data" / "api" / "ApiService.kt"
    output = project_root / "android_app" / "docs" / "ANDROID_API_CONTRACT.md"
    output.parent.mkdir(parents=True, exist_ok=True)

    backend_routes = parse_backend_routes(app_py)
    android_routes = parse_android_routes(api_service)
    output.write_text(build_markdown(backend_routes, android_routes), encoding="utf-8")
    print(f"Generated: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
